### ISSUE TITLE
Cannot install beepy-kbd

### ISSUE THREAD

**Issue by klundry** [ardangelo/beepy-ppa#1]
I have followed the instructions to clean the old source driver builds multiple times. Still, I always get error: please uninstall the old development bbqX0kbd module and it refuses to install. I'm not sure what else to do.

**Comment by ardangelo** [comment]
What is the output of `modprobe -n bbqX0kbd`? That is the command used to check to see if the old driver is still installed. If it outputs a path, make sure that the driver is removed from that path and that you ran `depmod -a` to rebuild the module lists.

**Comment by klundry** [comment]
Thank you for that tip. I ended up just flashing a new image and starting fresh and its working great now. But I will keep this in mind if I run into it again. Cheers!
