### ISSUE TITLE
Cannot install beepy-kbd or sharp-drm

### ISSUE THREAD

**Issue by ultrashea** [ardangelo/beepy-ppa#3]
I am attempting to set up a new Beepy, following the instructions available at https://github.com/ardangelo/beepy-ppa .  When 
the following command is run
`sudo apt-get -y install beepy-kbd sharp-drm`,
the following errors are output:
Setting up beepy-kbd (2.2-2) ...
Loading new beepy-kbd-2.2 DKMS files...
Building for 6.1.0-rpi4-rpi-v6 6.1.0-rpi4-rpi-v8
Building initial module for 6.1.0-rpi4-rpi-v6
Error! Bad return status for module build on kernel: 6.1.0-rpi4-rpi-v6 (armv6l)
Consult /var/lib/dkms/beepy-kbd/2.2/build/make.log for more information.
dpkg: error processing package beepy-kbd (--configure):
 installed beepy-kbd package post-installation script subprocess returned error exit status 10
Setting up sharp-drm (1.1-1) ...
Loading new sharp-drm-1.1 DKMS files...
Building for 6.1.0-rpi4-rpi-v6 6.1.0-rpi4-rpi-v8
Building initial module for 6.1.0-rpi4-rpi-v6
Error! Bad return status for module build on kernel: 6.1.0-rpi4-rpi-v6 (armv6l)
Consult /var/lib/dkms/sharp-drm/1.1/build/make.log for more information.
dpkg: error processing package sharp-drm (--configure):
 installed sharp-drm package post-installation script subprocess returned error exit status 10
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for libc-bin (2.36-9+rpt2+deb12u3) ...
Errors were encountered while processing:
 beepy-kbd
 sharp-drm
E: Sub-process /usr/bin/dpkg returned an error code (1)

Looking at the referenced make.log files, the following is seen:
/var/lib/dkms/beepy-kbd/2.2/build/make.log:
DKMS make.log for beepy-kbd-2.2 for kernel 6.1.0-rpi4-rpi-v6 (armv6l)
Wed 11 Oct 17:11:10 EDT 2023
make: Entering directory '/usr/src/linux-headers-6.1.0-rpi4-rpi-v6'
  CC [M]  /var/lib/dkms/beepy-kbd/2.2/build/src/main.o
  CC [M]  /var/lib/dkms/beepy-kbd/2.2/build/src/params_iface.o
  CC [M]  /var/lib/dkms/beepy-kbd/2.2/build/src/sysfs_iface.o
  CC [M]  /var/lib/dkms/beepy-kbd/2.2/build/src/input_iface.o
  CC [M]  /var/lib/dkms/beepy-kbd/2.2/build/src/input_meta.o
  CC [M]  /var/lib/dkms/beepy-kbd/2.2/build/src/input_display.o
  CC [M]  /var/lib/dkms/beepy-kbd/2.2/build/src/input_fw.o
  CC [M]  /var/lib/dkms/beepy-kbd/2.2/build/src/input_rtc.o
  LD [M]  /var/lib/dkms/beepy-kbd/2.2/build/beepy-kbd.o
make[1]: *** No rule to make target '/var/lib/dkms/beepy-kbd/2.2/build/beepy-kbd.dtbo', needed by '/var/lib/dkms/beepy-kbd/2.2/build/'.  Stop.
make: *** [/usr/src/linux-headers-6.1.0-rpi4-common-rpi/Makefile:2039: /var/lib/dkms/beepy-kbd/2.2/build] Error 2
make: Leaving directory '/usr/src/linux-headers-6.1.0-rpi4-rpi-v6'

/var/lib/dkms/sharp-drm/1.1/build/make.log:
DKMS make.log for sharp-drm-1.1 for kernel 6.1.0-rpi4-rpi-v6 (armv6l)
Wed 11 Oct 16:43:07 EDT 2023
make: Entering directory '/usr/src/linux-headers-6.1.0-rpi4-rpi-v6'
  CC [M]  /var/lib/dkms/sharp-drm/1.1/build/src/main.o
  CC [M]  /var/lib/dkms/sharp-drm/1.1/build/src/drm_iface.o
  CC [M]  /var/lib/dkms/sharp-drm/1.1/build/src/params_iface.o
  CC [M]  /var/lib/dkms/sharp-drm/1.1/build/src/ioctl_iface.o
  LD [M]  /var/lib/dkms/sharp-drm/1.1/build/sharp-drm.o
make[1]: *** No rule to make target '/var/lib/dkms/sharp-drm/1.1/build/sharp-drm.dtbo', needed by '/var/lib/dkms/sharp-drm/1.1/build/'.  Stop.
make: *** [/usr/src/linux-headers-6.1.0-rpi4-common-rpi/Makefile:2039: /var/lib/dkms/sharp-drm/1.1/build] Error 2
make: Leaving directory '/usr/src/linux-headers-6.1.0-rpi4-rpi-v6'

**Comment by soiboi** [comment]
Having the same exact issue.

**Comment by ultrashea** [comment]
I think I may have identified the source of the problem - when I installed the OS, I chose to use the most recent version of the Raspberry PI OS Lite image, which is based upon Debian Bookworm.  I just tried the process using the Legacy version of the OS, which is based on Debian Bullseye.  Using the legacy OS version results in beepy-kbd and sharp-drm being installed with no errors.

**Comment by soiboi** [comment]
Can confirm `beepy-kbd` and `sharp-drm` install without problems on Legacy. I guess we have to wait until `raspberrypi-kernel-headers` gets updated for the kernel shipping with the 2023-10-10 Bookworm release, which is 6.1.54 I believe. Or compile them ourselves with `rpi-source`, but I haven't looked into that yet.

**Comment by leoherzog** [comment]
Looks like they're not going to have the same package nomenclature in Bookworm.

https://github.com/raspberrypi/linux/issues/5643

Installation still fails, even with the `linux-headers-rpi-v8` package installed.

**Comment by ardangelo** [comment]
Hi all, I finally got back to this. I updated the packages to support changes in Debian 12, and they are working for me on both Debian 11 and 12 now. Please let me know if you are seeing any more problems.

**Comment by leoherzog** [comment]
@ardangelo Still having this issue on a fresh install of Raspberry Pi OS 12 Lite (64 bit, `raspios_armhf-2024-07-04`)

```shell
$ curl -s --compressed "https://ardangelo.github.io/beepy-ppa/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/beepy.gpg >/dev/null

$ sudo curl -s --compressed -o /etc/apt/sources.list.d/beepy.list "https://ardangelo.github.io/beepy-ppa/beepy.list"

$ sudo apt update

Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian-security bookworm-security InRelease      
Hit:3 http://archive.raspberrypi.com/debian bookworm InRelease               
Hit:4 http://deb.debian.org/debian bookworm-updates InRelease       
Get:5 https://ardangelo.github.io/beepy-ppa ./ InRelease [3,156 B]
Get:6 https://ardangelo.github.io/beepy-ppa ./ Packages [10.5 kB]
Fetched 13.7 kB in 3s (4,723 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.

$ sudo apt -y install beepy-kbd sharp-drm
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  beepy-fw beepy-symbol-overlay dkms i2c-tools libi2c0 linux-headers-6.1.0-23-arm64 linux-headers-6.1.0-23-common
  linux-headers-arm64 linux-kbuild-6.1 read-edid
Suggested packages:
  menu libi2c-dev python3-smbus
The following NEW packages will be installed:
  beepy-fw beepy-kbd beepy-symbol-overlay dkms i2c-tools libi2c0 linux-headers-6.1.0-23-arm64
  linux-headers-6.1.0-23-common linux-headers-arm64 linux-kbuild-6.1 read-edid sharp-drm
0 upgraded, 12 newly installed, 0 to remove and 0 not upgraded.
Need to get 13.1 MB of archives.
After this operation, 67.1 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main arm64 dkms all 3.0.10-8+deb12u1 [48.7 kB]
Get:2 http://deb.debian.org/debian bookworm/main arm64 libi2c0 arm64 4.3-2+b3 [9,456 B]                                
Get:3 http://deb.debian.org/debian bookworm/main arm64 i2c-tools arm64 4.3-2+b3 [78.6 kB]
Get:4 http://deb.debian.org/debian-security bookworm-security/main arm64 linux-headers-6.1.0-23-common all 6.1.99-1 [10.0 MB]
Get:5 http://archive.raspberrypi.com/debian bookworm/main arm64 linux-kbuild-6.1 arm64 1:6.1.73-1+rpt1 [913 kB]
Get:6 https://ardangelo.github.io/beepy-ppa ./ beepy-fw 3.8-1 [49.5 kB]                                            
Get:7 https://ardangelo.github.io/beepy-ppa ./ sharp-drm 1.5-7 [21.6 kB]                                               
Get:8 https://ardangelo.github.io/beepy-ppa ./ beepy-kbd 2.11-4 [42.5 kB]                                              
Get:9 https://ardangelo.github.io/beepy-ppa ./ beepy-symbol-overlay 1.2-3 [492 kB]                                     
Get:10 http://deb.debian.org/debian-security bookworm-security/main arm64 linux-headers-6.1.0-23-arm64 arm64 6.1.99-1 [1,385 kB]
Get:11 http://deb.debian.org/debian-security bookworm-security/main arm64 linux-headers-arm64 arm64 6.1.99-1 [1,420 B]
Get:12 http://deb.debian.org/debian bookworm/main arm64 read-edid arm64 3.0.2-1.1 [16.1 kB]
Fetched 13.1 MB in 6s (2,175 kB/s)                                                                                     
Selecting previously unselected package dkms.
(Reading database ... 56042 files and directories currently installed.)
Preparing to unpack .../00-dkms_3.0.10-8+deb12u1_all.deb ...
Unpacking dkms (3.0.10-8+deb12u1) ...
Selecting previously unselected package libi2c0:arm64.
Preparing to unpack .../01-libi2c0_4.3-2+b3_arm64.deb ...
Unpacking libi2c0:arm64 (4.3-2+b3) ...
Selecting previously unselected package i2c-tools.
Preparing to unpack .../02-i2c-tools_4.3-2+b3_arm64.deb ...
Unpacking i2c-tools (4.3-2+b3) ...
Selecting previously unselected package linux-headers-6.1.0-23-common.
Preparing to unpack .../03-linux-headers-6.1.0-23-common_6.1.99-1_all.deb ...
Unpacking linux-headers-6.1.0-23-common (6.1.99-1) ...
Selecting previously unselected package linux-kbuild-6.1.
Preparing to unpack .../04-linux-kbuild-6.1_1%3a6.1.73-1+rpt1_arm64.deb ...
Unpacking linux-kbuild-6.1 (1:6.1.73-1+rpt1) ...
Selecting previously unselected package linux-headers-6.1.0-23-arm64.
Preparing to unpack .../05-linux-headers-6.1.0-23-arm64_6.1.99-1_arm64.deb ...
Unpacking linux-headers-6.1.0-23-arm64 (6.1.99-1) ...
Selecting previously unselected package linux-headers-arm64.
Preparing to unpack .../06-linux-headers-arm64_6.1.99-1_arm64.deb ...
Unpacking linux-headers-arm64 (6.1.99-1) ...
Selecting previously unselected package read-edid.
Preparing to unpack .../07-read-edid_3.0.2-1.1_arm64.deb ...
Unpacking read-edid (3.0.2-1.1) ...
Selecting previously unselected package beepy-fw.
Preparing to unpack .../08-beepy-fw_3.8-1_arm64.deb ...
Unpacking beepy-fw (3.8-1) ...
Selecting previously unselected package sharp-drm.
Preparing to unpack .../09-sharp-drm_1.5-7_arm64.deb ...
error: CONF_SWAPSIZE detected as 200
Please edit /etc/dphys-swapfile, increase to at least 512, and reboot
dpkg: error processing archive /tmp/apt-dpkg-install-xMjUoz/09-sharp-drm_1.5-7_arm64.deb (--unpack):
 new sharp-drm package pre-installation script subprocess returned error exit status 1
Selecting previously unselected package beepy-kbd.
Preparing to unpack .../10-beepy-kbd_2.11-4_arm64.deb ...
error: CONF_SWAPSIZE detected as 200
Please edit /etc/dphys-swapfile, increase to at least 512, and reboot
dpkg: error processing archive /tmp/apt-dpkg-install-xMjUoz/10-beepy-kbd_2.11-4_arm64.deb (--unpack):
 new beepy-kbd package pre-installation script subprocess returned error exit status 1
Selecting previously unselected package beepy-symbol-overlay.
Preparing to unpack .../11-beepy-symbol-overlay_1.2-3_arm64.deb ...
Unpacking beepy-symbol-overlay (1.2-3) ...
Errors were encountered while processing:
 /tmp/apt-dpkg-install-xMjUoz/09-sharp-drm_1.5-7_arm64.deb
 /tmp/apt-dpkg-install-xMjUoz/10-beepy-kbd_2.11-4_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by andrewbeard** [comment]
@leoherzog Yours looks like an entirely different issue, but the error message says exactly what to do to fix it:

```
error: CONF_SWAPSIZE detected as 200
Please edit /etc/dphys-swapfile, increase to at least 512, and reboot
dpkg: error processing archive /tmp/apt-dpkg-install-xMjUoz/09-sharp-drm_1.5-7_arm64.deb (--unpack):
 new sharp-drm package pre-installation script subprocess returned error exit status 1
```

Increase your swap file size as described, restart, and try again.
